#pragma once

#define GAME_ECS entity_component_system<calendar_component, debug_name_component, obstruction_component, position_component, power_battery_component, power_generator_component, renderable_component, settler_ai_component, viewshed_component, game_stats_component, game_species_component, game_health_component, provisions_component, item_storage_component, item_carried_component>
#define GAME_MSG message_bus<command_message, power_consumed_message, chat_emote_message, mouse_motion_message>
