stockpiles = {
    kit = { name = "Kits", id = 22 },
    tool = { name = "Tools", id = 1 },
    wood = { name = "Wood", id = 2 },
    stone = { name = "Stone", id = 3 },
    ore = { name = "Ores", id = 4 },
    powder = { name = "Powders", id = 5 },
    sand = { name = "Sand", id = 6 },
    oil = { name = "Oil", id = 7 },
    soil = { name = "Soil", id = 8 },
    fuel = { name = "Fuel", id = 9 },
    glass = { name = "Glass", id = 10 },
    silicon = { name = "Silicon", id = 11 },
    waste = { name = "Waste", id = 12 },
    block = { name = "Building blocks", id = 13 },
    furniture = { name = "Furniture", id = 14 },
    food = { name = "Food", id = 15 },
    weapon = { name = "Weapons", id = 16 },
    ammo = { name = "Ammo", id = 17 },
    component = { name = "Components", id = 18 },
    bone = { name = "Bones", id = 19 },
    leather = { name = "Leather", id = 20 },
    clothing = { name = "Clothing", id = 21 },
    fodder = { name = "Fodder", id = 22 },
    thread = { name = "Thread", id = 23 },
    manure = { name = "Manure", id = 24 },
    seeds = { name = "Seeds", id = 25 },
}