vegetation = {
    dummy_grass = { name = "Grass", glyph = glyphs['apostrophe'], fg=colors['white'], bg=colors['black'], provides = "hay" },
    grass = { name = "Grass", glyph = glyphs['grass'], fg=colors['white'], bg=colors['black'], provides = "hay" },
    grass_short = { name = "Short Grass", glyph = glyphs['grass_sparse'], fg=colors['white'], bg=colors['black'], provides = "hay" },
    grass_long = { name = "Long Grass", glyph = glyphs['grass_long'], fg=colors['white'], bg=colors['black'], provides = "hay" },
    
    reeds = { name = "Reeds", glyph = glyphs['reeds'], fg=colors['white'], bg=colors['black'], provides = "thread" },

    artichoke = { name = "Artichoke", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "artichoke_veg" },
    asparagus = { name = "Asparagus", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "asparagus_veg" },
    bambara_groundnut = { name = "Bambara Groundnut", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "bambara_nut" },
    string_bean = { name = "String Bean", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "string_bean_veg" },
    broad_bean = { name = "Broad Bean", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "broad_bean_veg" },
    beetroot = { name = "Beetroot", glyph = glyphs['flower_small'], fg=colors['dark_red'], bg=colors['black'], provides = "beetroot_veg" },
    goya = { name = "Goya", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "goya_veg" },
    cabbage = { name = "Cabbage", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "cabbage_veg" },
    caper = { name = "Caper", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "caper_veg" },
    carrot = { name = "Caper", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "carrot_veg" },
    cassava = { name = "Cassava", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "cassava_veg" },
    celery = { name = "Celery", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "celergy_veg" },
    chickpea = { name = "Chickpea", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "chickpea_veg" },
    chickory = { name = "Chickory", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "chickory_herb" },
    cowpea = { name = "Cowpea", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "cowpea_veg" },
    cucumber = { name = "Cucumber", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "cucumber_veg" },
    eggplant = { name = "Eggplant", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "eggplant_veg" },
    cress = { name = "Cress", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "cress_veg" },
    garlic = { name = "Garlic", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "garlic_herb" },
    horned_melon = { name = "Horned Melon", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "melon_veg" },
    leek = { name = "Leek", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "leek_veg" },
    lentil = { name = "Lentil", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "lentil_veg" },
    lettuce = { name = "Lettuce", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "lettuce_veg" },
    mung_bean = { name = "Mung Bean", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "mung_bean_veg" },
    onion = { name = "Onion", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "onion_veg" },
    parsnip = { name = "Parsnip", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "parsnip_veg" },
    pea = { name = "Pea", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "pea_veg" },
    peanut = { name = "Peanut", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "peanut_veg" },
    pepper = { name = "Pepper", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "pepper_veg" },
    potato = { name = "Potato", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "potato_veg" },
    radish = { name = "Radish", glyph = glyphs['flower_small'], fg=colors['magenta'], bg=colors['black'], provides = "radish_veg" },
    red_bean = { name = "Red Bean", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "red_bean_veg" },
    rhubarb = { name = "Rhubarb", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "rhubarb_herb" },
    soybean = { name = "Soybean", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "soybean_veg" },
    spinach = { name = "Spinach", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "spinach_veg" },
    squash = { name = "Squash", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "squash_veg" },
    sweet_potato = { name = "Sweet Potato", glyph = glyphs['flower_small'], fg=colors['wood_brown'], bg=colors['black'], provides = "sweet_potato_veg" },
    tomato = { name = "Tomato", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "tomato_fruit" },
    tomatillo = { name = "Tomatillo", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "tomatillo_veg" },
    turnip = { name = "Turnip", glyph = glyphs['flower_small'], fg=colors['magenta'], bg=colors['black'], provides = "turnip_veg" },
    watermelon = { name = "Watermelon", glyph = glyphs['flower_small'], fg=colors['white'], bg=colors['black'], provides = "watermelon_veg" },
    yam = { name = "Yam", glyph = glyphs['flower_small'], fg=colors['wood_brown'], bg=colors['black'], provides = "yam_veg" },
    strawberry = { name = "Strawberry", glyph = glyphs['flower_small'], fg=colors['red'], bg=colors['black'], provides = "strawberry_fruit" },

    lavendar = { name = "Lavendar", glyph = glyphs['flower_purple'], fg=colors['white'], bg=colors['black'], provides = "lavendar_herb" },
    sage = { name = "Sage", glyph = glyphs['bush'], fg=colors['white'], bg=colors['black'], provides = "sage_herb" },

    daisy = { name = "Daisy", glyph = glyphs['flower_yellow'], fg=colors['white'], bg=colors['black'] },
    heather = { name = "Heather", glyph = glyphs['flower_purple'], fg=colors['white'], bg=colors['black'] }
}
