#pragma once

#include "map_render_system.hpp"
#include "calendar_system.hpp"
#include "settler_ai_system.hpp"
#include "panel_render_system.hpp"
#include "mining_system.hpp"
#include "inventory_system.hpp"
#include "visibility_system.hpp"
#include "workflow_system.hpp"
#include "topology_system.hpp"
#include "camera_system.hpp"
#include "renderables_system.hpp"
#include "lighting_system.hpp"
#include "power_system.hpp"
#include "damage_system.hpp"
#include "wildlife_population_system.hpp"
#include "movement_system.hpp"
