#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <set>
#include <vector>
#include <unordered_map>
#include <map>
#include <unordered_set>
#include <bitset>
#include <memory>
#include <functional>
#include <algorithm>
#include <fstream>
#include <chrono>
#include <sstream>
#include <iomanip>
#include <queue>
#include <future>
#include <mutex>
#include <typeinfo>
#include <atomic>
#include <array>
#include <sstream>
#include <thread>
#include <boost/container/flat_map.hpp>
#include <utility>
#include <stdexcept>
#include <fstream>
#include <mutex>
#include <cctype>
